Twilio verify devise Readme part 1
MidwestAccessCoalition/twilio-verify-devise pull request #108
Opened 2024-06-12 16:33 UTC by camckin10

Breaking up Twilio Verify Devise Readme edits into chunks

2024-06-12 17:30 UTC, wwahammy requested changes

2024-06-13 17:15 UTC, camckin10 commented on README.md
> +----------------------------------------------------------
@wwahammy I am unclear about the question. Are you asking how the gem readme was created, or are you asking how the gem itself was created?

2024-06-13 19:08 UTC, wwahammy commented on README.md
> +----------------------------------------------------------
I'm asking how the contents of this were created.

2024-07-10 19:16 UTC, camckin10 commented on README.md
> +----------------------------------------------------------
I believe this is from the initial readme. I can clean it up.

2024-07-10 19:27 UTC, camckin10 commented
@wwahammy  I am actually going to close this PR because the initial proper Twilio verify repo does not have this content.

2024-07-10 19:27 UTC, closed without merging