Twilio Verify Devise Readme --- Readme Sections
MidwestAccessCoalition/twilio-verify-devise pull request #109
Opened 2024-06-12 16:48 UTC by camckin10

2024-06-13 19:38 UTC, wwahammy requested changes
Looks just about right. One minor change and this is good to go.

2024-06-13 19:38 UTC, wwahammy commented on README.md
>  * [Verify API reference](https://www.twilio.com/docs/verify/api)
I'd remove these as you don't need to know them to understand how to use the software.

2024-07-12 17:49 UTC, wwahammy requested changes

2024-07-12 17:49 UTC, wwahammy commented on README.md
> -  * [Request a phone call](#request-a-phone-call)
Request a phone call was readded by https://github.com/MidwestAccessCoalition/twilio-verify-devise/pull/97 so it should be kept.

2024-08-12 15:05 UTC, BintLopez approved these changes
🦑

2024-08-12 19:16 UTC, wwahammy approved these changes

2024-08-12 19:16 UTC, merged