Twilio Verify Readme -- Pre-requisites
MidwestAccessCoalition/twilio-verify-devise pull request #110
Opened 2024-06-12 16:51 UTC by camckin10

2024-06-12 17:29 UTC, wwahammy requested changes

2024-06-12 17:29 UTC, wwahammy commented on README.md
> +Create an [Twilio Verify Application in the Twilio console](https://www.twilio.com/console/authy/applications) and take note of the API key.
This isn't the Twilio Verify console URL; this is the one for creating an Authy application which doesn't exist anymore.

2024-06-12 17:29 UTC, wwahammy commented on README.md
> +First get your Twilio Verify API key from [the Twilio console](https://www.twilio.com/console/authy/applications). We recommend you store your API key as an environment variable.
Not the right URL

2024-06-12 17:29 UTC, wwahammy commented on README.md
> +gem 'devise-twilio-verify'
Please correct the name of the gem. Additionally, we haven't uploaded to rubygems.org, so we need to use the git parameter for the gem requirement. I recommend the following:
 ```suggestion
gem 'devise-authy', git: 'https://github.com/MidwestAccessCoalition/twilio-verify-devise.git'
```

2024-06-12 17:29 UTC, wwahammy commented on README.md
> +    rails g devise_twilio_verify:install
We haven't renamed the generator (https://github.com/MidwestAccessCoalition/twilio-verify-devise/blob/main/lib/generators/devise_authy/install_generator.rb). It's still called devise_authy:install

2024-06-12 17:29 UTC, wwahammy commented on README.md
> +rails g devise_twilio_verify [MODEL_NAME]
We didn't rename the generator, it's still called devise_authy https://github.com/MidwestAccessCoalition/twilio-verify-devise/blob/main/lib/generators/devise_authy/devise_authy_generator.rb

2024-06-12 17:29 UTC, wwahammy commented on README.md
> +To support account locking (recommended), you must add `:twilio_verify_lockable` to the `devise :twilio_verify_authenticatable, ...` configuration in your model as this is not yet supported by the ge
We didn't rename these to "twilio_verify_lockable" and "twilio_verify_authenticatable" yet.

2024-06-12 17:29 UTC, wwahammy commented on README.md
> +end
I don't really know where this came from. It's not accurate, we're still using the authy_id and if the field was removed by the user, it wouldn't work.

2024-06-12 17:29 UTC, wwahammy commented on README.md
> +	:verify_twilio_verify_installation => "/verify-installation"
There are no paths matching these. We haven't renamed the paths.

2024-06-13 19:41 UTC, wwahammy requested changes

2024-06-13 19:41 UTC, wwahammy commented on README.md
> +	:verify_twilio_verify_installation => "/verify-installation"
Again, there are no path names called :verify_twilio_verify, :enable_twilio_verify, etc.

2024-07-12 17:48 UTC, wwahammy requested changes

2024-07-12 17:48 UTC, wwahammy commented on README.md
> -```
This is still accurate and should be kept.

2024-07-12 17:48 UTC, wwahammy commented on README.md
> -
Yes, please delete this.

2024-08-12 15:05 UTC, BintLopez approved these changes
🦑

2024-08-12 19:17 UTC, wwahammy approved these changes

2024-08-12 19:17 UTC, merged